
# Motivating functions

AS said in R4ds:

> Writing a function has three big advantages over using copy-and-paste:
>
> 1.  You can give a function an evocative name that makes your code
>     easier to understand.
>
> 2.  As requirements change, you only need to update code in one place,
>     instead of many.
>
> 3.  You eliminate the chance of making incidental mistakes when you
>     copy and paste (i.e. updating a variable name in one place, but
>     not in another).
>
> Writing good functions is a lifetime journey. Even after using R for
> many years I still learn new techniques and better ways of approaching
> old problems.

-   the myth of "I'll only need to do this once"
-   The myth of "There's not enough time to write functions"
-   copy-pasting code or having a "cheat sheet of code to help do
    things" is an activity that I do not advocate for. The reason is
    that these cheat sheets should be written as functions, as things
    that encapsulate. If you are copying and pasting all the time, then
    all you are doing is spreading around insanity. You are accumulating
    technical debt that comes with crushing interest rates: your time,
    and your energy.
